### ISSUE TITLE
struct has no exported member 'StructType'

### ISSUE THREAD

**Issue by johnbaro** [sarakusha/novastar#591] opened 2022-10-14 05:07 UTC
- **I'm submitting a ...**
  [X ] bug report
  
- **Summary**
Importing `@novastar/serial` results in an import error as below.

```
node_modules/@novastar/codec/build/main/lib/Packet.d.ts:44:53 - error TS2694: Namespace '"/workspaces/Novastar/node_modules/@novastar/codec/node_modules/typed-struct/build/main/struct"' has no exported member 'StructType'.
44 export declare const Packet: import("typed-struct").StructType<{
Found 1 error in node_modules/@novastar/codec/build/main/lib/Packet.d.ts:44
```

- **Other information** 
Version: 2.0.0-alpha.6

**Comment by sarakusha** [comment] 2022-10-14 06:58
I have released an updated version. 2.0.0-alpha.7

**Comment by sarakusha** [comment] 2022-10-21 09:14
If the problem is solved, I close the issue.

**Closed by sarakusha** 2022-10-21 09:14 UTC
